spring:
  application:
    name: service-app
  cloud:
    consul:
      host: localhost
      port: 8500
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    host: localhost
    password: 123456
    port: 5672
    username: springcloud
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/config-server-db
    username: root
  flyway:
    locations: /schema

