spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
  redis:
    host: localhost
    password: admin

