mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8899
feign:
  sentinel:
    enabled: true
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  scan:
    base-packages: com.firepongo.chaos.service
  cloud:
    subscribed-services:
spring:
  application:
    name: chaos-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8720
        dashboard: 127.0.0.1:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
  redis:
    database: 3
    port: 6379
    timeout: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    com:
      favorites: DEBUG
    org:
      hibernate: ERROR
      springframework:
        web: INFO
