spring:
  datasource:
    url: jdbc:mysql://firepongo.tech:3306/chaos?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: firepongo
  redis:
    database: 0
    host: firepongo.tech
    password: firepongo
  dubbo:
    registry:
      address: zookeeper://firepongo.tech:2181
    consumer:
      check: false
  rabbitmq:
    addresses: firepongo.tech
    username: admin
    password: firepongo
zipkin:
  serviceName: local-boot-web
xxl:
  job:
    executor:
      appname: local-boot-executor
