version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: c-nginx
    volumes:
      - ./nginx/www/:/usr/share/nginx/html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    restart: always
    networks:
      - cui-ci
  redis:
    image: redis:latest
    container_name: c-redis
    restart: always
    command: redis-server --requirepass firepongo!tech
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - cui-ci
  rabbitmq:
    image: rabbitmq:management
    container_name: c-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=firepongo!tech
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - cui-ci
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  zookeeper:
    image: zookeeper:latest
    container_name: c-zookeeper
    networks:
      - cui-ci
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper:/conf/
    restart: always
  dubbo-admin:
    image: firepongo.tech:8288/cui/dubbo-admin:latest
    container_name: c-dubbo-admin
    networks:
      - cui-ci
    links:
      - zookeeper:zookeeper
    depends_on:
      - zookeeper
    ports:
      - 18888:18888
    restart: always
networks:
  cui-ci:
    driver: bridge
