app:
  admin:
    username: "chaos-manage-dev"
    password: "chaos-manage-dev"
spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: admin
    password: admin
  redis:
    host: 127.0.0.1
    password:


