app:
  admin:
    host: "http://127.0.0.1:38089"
    username: "chaos-manage-local"
    password: "chaos-manage-local"
spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: admin
    password: admin
  redis:
    host: 127.0.0.1
    password:

