app:
  admin:
    username: "order-manage-dev"
    password: "order-manage-dev"
spring:
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin
  redis:
    host: localhost
    password: admin

